### ISSUE TITLE
Zone names from classless delegations (RFC 2317) not accepted

### ISSUE THREAD

**Issue by stirnim** [zonemaster/zonemaster-backend#951]
The zonemaster.net UI does not accept zone names from classless delegation (RFC 2317).

Web UI error:
Internal server error

Zone name used for testing:
192/26.26.176.195.in-addr.arpa.

**Comment by matsduf** [comment]
Resolved by #969 and is now available in the v2022.1 release.

**Comment by vcunat** [comment]
We still see errors with the latest zonemaster versions, e.g.:
https://zonemaster.nic.cz/en/result/b5c9c145622d2d3a
https://zonemaster.nic.cz/en/result/8fa76fed8b144f09

Are we missing something?

**Comment by matsduf** [comment]
The second link shows a test of a non-zone. That is why it returns an error (CRITICAL).

The second link shows complaint about "/" in a zone name. Before the change in #969 the zone was not tested at all if it contained a "/". Now it does. But [Syntax01] still complaints about "/". That test case needs an update, especially to produce better messages. I will create an issue on that.

[Syntax01]: https://doc.zonemaster.net/latest/specifications/tests/Syntax-TP/syntax01.html
